apiVersion: apps/v1          ## The version of the Kubernetes API
kind: Deployment                     ## The type of object for jobs

metadata:
 name: web-app

spec:                         ## What state you desire for the object
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: web-app 
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: web-app
        app.kubernetes.io/component: web
    spec:
      containers:
      - name: webapp
        image: maxrok98/docker-webappdb-example:latest                  ##  Image used
        ports:
          - containerPort: 80
            name: http-web-svc