apiVersion: v1
kind: Service
metadata:
  name: web-app

spec:
  type: NodePort #LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32000
    protocol: TCP
  selector:
    app: web-app